services:
  base:
    image: microros/base:rolling
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42
    volumes:
      - ../..:/workspaces:cached

  serial-agent0:
    container_name: serial-agent0
    image: microros/micro-ros-agent:jazzy
    network_mode: host
    privileged: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=0
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: serial --dev /dev/ttyUSB0
    restart: unless-stopped

  udp-agent:
    container_name: udp-agent0
    image: microros/micro-ros-agent:rolling
    network_mode: host
    privileged: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=0
    command: udp4 --port 9999
    restart: unless-stopped